git:
    depth: 10
    
# required to get an OSX environment
language: objective-c

env:
    - TERM=dumb

before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"

  # Get hold of ANT.
  - brew update
  - brew install ant

  # Adobe Flash Player for CLI
  - brew update >brew-update.log
  - brew install ant gradle >brew-install.log
  - brew install caskroom/cask/brew-cask
  - brew tap caskroom/versions
  - brew cask install flash-player-debugger

  # Set env. variable used by FlexUnit
  - export FLASH_PLAYER_EXE="/Applications/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger"

script:
  - cd core && ant
  - cd ../examples/simpleMVC && ant
